sudo: required
language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
before_install:
    - sudo apt-get update
    - sudo pip install --upgrade pip
    - sudo pip install python3
install:
  - sudo pip install awscli
before_script:
  - npm install
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  bucket: S3_BUCKET
  skip_cleanup: true
  local-dir: public
  acl: public_read
  cache_control: 'max-age=21600'
after_success:
branches:
  only:
    - master
    - develop