sudo: required
language: python
python:
  - "3.6.5"
# language: node_js
# node_js:
#   - '10'
# cache:
#   directories:
#     - node_modules
before_install:
    - sudo apt-get update
install:
    - pip install awscli
# before_script:
#   - npm install
# script:
#   - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  local-dir: public
  acl: public_read
  cache_control: "max-age=21600"
after_success:
branches:
  only:
    - master
    - develop
before_deploy:
  - aws s3 rm s3://$S3_BUCKET --recursive
### Forcing AWS CloudFront to refresh its cache
after_deploy:
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"